language: scala
scala:
  - 2.12.4
services:
  - postgresql

postgresql: "9.4"

before_script:
  - ./src/main/resources/db/create.sh 127.0.0.1 5432 postgres

script:
  - sbt flywayMigrate
  - sbt test  
